version: '3.9'
services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./public-service-catalog.pb:/transcoders/public-service-catalog.pb
      - ./criminal-cert-service.pb:/transcoders/criminal-cert-service.pb
    extra_hosts:
      - 'auth-grpc:172.17.0.1'
      - 'criminal-cert-grpc:172.17.0.1'
      - 'public-service-catalog-grpc:172.17.0.1'
    ports:
      - 9090:9090
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'heidiks/rabbitmq-delayed-message-exchange'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  mongo1:
    container_name: mongo1
    image: mongo:5
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "diia"
      ]
  mongo2:
    container_name: mongo2
    image: mongo:5
    networks:
      - mongo-network
    ports:
      - 27018:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "diia"
      ]
  mongo3:
    container_name: mongo3
    image: mongo:5
    networks:
      - mongo-network
    ports:
      - 27019:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "diia"
      ]

networks:
  mongo-network:
    driver: bridge
